from app.schemas.common import CoreBaseModel, MessageResponse, PaginatedResponse
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserInterestCreate,
    UserInterestResponse,
    UserInterestsUpdate,
)
from app.schemas.taxonomy import (
    DomainBase,
    DomainCreate,
    DomainUpdate,
    DomainResponse,
    DomainWithSubDomainsResponse,
    SubDomainBase,
    SubDomainCreate,
    SubDomainUpdate,
    SubDomainResponse,
)
from app.schemas.course import (
    LessonBase,
    LessonCreate,
    LessonUpdate,
    LessonResponse,
    ModuleBase,
    ModuleCreate,
    ModuleUpdate,
    ModuleResponse,
    ModuleDetailResponse,
    CourseBase,
    CourseCreate,
    CourseUpdate,
    CourseResponse,
    CourseDetailResponse,
)
from app.schemas.quiz import (
    QuestionOptionBase,
    QuestionOptionCreate,
    QuestionOptionResponse,
    QuestionOptionPublicResponse,
    QuestionBase,
    QuestionCreate,
    QuestionUpdate,
    QuestionResponse,
    QuestionPublicResponse,
    QuizBase,
    QuizCreate,
    QuizUpdate,
    QuizResponse,
    QuizPublicResponse,
    AIQuizDraftBase,
    AIQuizDraftCreate,
    AIQuizDraftUpdate,
    AIQuizDraftResponse,
)
from app.schemas.enrollment import (
    LessonProgressResponse,
    LessonProgressUpdate,
    ModuleProgressResponse,
    EnrollmentCreate,
    EnrollmentResponse,
    CourseProgressResponse,
)
from app.schemas.assessment import (
    QuizAnswerSubmit,
    QuizSubmissionRequest,
    QuestionResultResponse,
    QuizAttemptResponse,
    QuizSubmissionResultResponse,
    CertificateClaimRequest,
    CertificateResponse,
    CertificateVerifyResponse,
)

__all__ = [
    # Common
    "CoreBaseModel",
    "MessageResponse",
    "PaginatedResponse",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInterestCreate",
    "UserInterestResponse",
    "UserInterestsUpdate",
    # Taxonomy
    "DomainBase",
    "DomainCreate",
    "DomainUpdate",
    "DomainResponse",
    "DomainWithSubDomainsResponse",
    "SubDomainBase",
    "SubDomainCreate",
    "SubDomainUpdate",
    "SubDomainResponse",
    # Course
    "LessonBase",
    "LessonCreate",
    "LessonUpdate",
    "LessonResponse",
    "ModuleBase",
    "ModuleCreate",
    "ModuleUpdate",
    "ModuleResponse",
    "ModuleDetailResponse",
    "CourseBase",
    "CourseCreate",
    "CourseUpdate",
    "CourseResponse",
    "CourseDetailResponse",
    # Quiz
    "QuestionOptionBase",
    "QuestionOptionCreate",
    "QuestionOptionResponse",
    "QuestionOptionPublicResponse",
    "QuestionBase",
    "QuestionCreate",
    "QuestionUpdate",
    "QuestionResponse",
    "QuestionPublicResponse",
    "QuizBase",
    "QuizCreate",
    "QuizUpdate",
    "QuizResponse",
    "QuizPublicResponse",
    "AIQuizDraftBase",
    "AIQuizDraftCreate",
    "AIQuizDraftUpdate",
    "AIQuizDraftResponse",
    # Enrollment
    "LessonProgressResponse",
    "LessonProgressUpdate",
    "ModuleProgressResponse",
    "EnrollmentCreate",
    "EnrollmentResponse",
    "CourseProgressResponse",
    # Assessment
    "QuizAnswerSubmit",
    "QuizSubmissionRequest",
    "QuestionResultResponse",
    "QuizAttemptResponse",
    "QuizSubmissionResultResponse",
    "CertificateClaimRequest",
    "CertificateResponse",
    "CertificateVerifyResponse",
]
